name: Reminder Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Run reminder script
        run: php check_reminders.php
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}