name: Reminder Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Run reminder script
        run: php check_reminders.php
